# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # CHECK that required plugin is installed
  unless Vagrant.has_plugin?("vagrant-vbguest")
    errorMsg = <<-END

     ********************************************************************************
     Please install the plugin vagrant-vbguest.
     The plugin can be installed using the following command:
        
        vagrant plugin install vagrant-vbguest

     ********************************************************************************

    END
    raise errorMsg
  end
  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "puppetlabs/centos-7.0-64-puppet"
  config.vm.box_download_insecure = false

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  config.vm.network "forwarded_port", guest: 9200, host: 19200
  #config.vm.network "public_network", auto_config: true

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
     vb.gui = false
  
    # Customize the amount of memory on the VM:
    vb.memory = "2048"
  end
 
  # WARNING: The following does not work with Vagrant 1.7.4/Puppet 4.x
  #config.vm.provision "puppet" do |puppet|
  #  puppet.module_path = "puppet/modules"
  #  puppet.manifests_path = "puppet/manifests"
  #end

  # So use a hack instead :(
  config.vm.provision "shell",  
    inline: "/opt/puppetlabs/bin/puppet apply --modulepath=/vagrant/puppet/modules /vagrant/puppet/manifests/site.pp"

end

